# Generated by Django 5.0.7 on 2024-07-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='isComplete',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(choices=[('3days_stretching', '3days_stretching'), ('7days_stretching', '7days_stretching'), ('30days_stretching', '30days_stretching'), ('3days_practicing', '3days_practicing'), ('7days_practicing', '7days_practicing'), ('30days_practicing', '30days_practicing')], max_length=20),
        ),
    ]
