# Generated by Django 5.0.7 on 2024-07-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stretching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailychallenge',
            name='date',
            field=models.DateField(auto_now_add=True, default="20240722"),
            preserve_default=False,
        ),
    ]
