# Generated by Django 5.0.7 on 2024-07-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stretching', '0002_dailychallenge_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailychallenge',
            name='date',
        ),
    ]
