# Generated by Django 5.0.7 on 2024-07-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stretching', '0003_remove_dailychallenge_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychallenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
